# Generated by Django 5.0.4 on 2024-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.CharField(max_length=200)),
                ('emp_password', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
            ],
        ),
    ]
