# Generated by Django 5.0.4 on 2024-06-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=200)),
                ('or_img', models.ImageField(upload_to='')),
                ('or_name', models.CharField(max_length=200)),
                ('or_price', models.IntegerField()),
                ('or_adrs', models.CharField(max_length=200)),
                ('or_ph', models.CharField(max_length=200)),
            ],
        ),
    ]
